# -*- coding: utf-8 -*-
"""LIST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kX2goM4g9WZ5eKt_ecwDzERiFmjajrQU
"""

#=============================
#saya akan memasukan benda apa saja yang saya perlukan untuk kuliah online
laptop = input("masukan merk laptop :")
keyboard = input("masukan merk keyboard :")
mouse = input("masukan merk mouse :")
#=============================
#saya akan masukan tipe yang saya pakai
tipe_laptop = int(input("masukan tipe laptop :"))
tipe_keyboard = int(input("masukan tipe keyboard :"))
#=============================
#saya akan masukan berapa harga yang saya pakai
harga_laptop = float(input("masukan harga laptop :"))
harga_keyboard = float(input("masukan harga keyboard :"))
harga_mouse = float(input("masukan harga mouse :"))
#=============================
#saya akan me-list semua benda yang saya pakai
list = []
#=============================
#laptop
list.append(laptop)
list.append(tipe_laptop)
list.append(harga_laptop)
#=============================
#keyboard
list.append(keyboard)
list.append(tipe_keyboard)
list.append(harga_keyboard)
#=============================
#mouse
list.append(mouse)
list.append(harga_mouse)
#=============================
#kita print semua list diatas
print("laptop :", list[0], ",", "tipe :", list[1], ",", "harga :", list[2])
print("keyboard :", list[3], ",", "tipe :", list[4], ",", "harga :", list[5])
print("mouse :", list[6], ",", "harga :", list[7])
#=============================
#kita print lagi berberapa variabel benda dan kita ingin mengetahui tipe datanya
#<<<<<<<<<<<<<<<<<<
#data string
print("variabel laptop yaitu             :", laptop, "tipe datanya yaitu           :", type(laptop),        end="\n\n")
print("variabel keyboard yaitu           :", laptop, "tipe datanya yaitu           :", type(keyboard),      end="\n\n")
print("variabel mouse yaitu              :", laptop, "tipe datanya yaitu           :", type(mouse),         end="\n\n")
#>>>>>>>>>>>>>>>>>>
#data integer
print("variabel tipe laptop yaitu        :", tipe_laptop, "tipe datanya yaitu      :", type(tipe_laptop),   end="\n\n")
print("variabel tipe keyboard yaitu      :", tipe_keyboard, "tipe datanya yaitu    :", type(tipe_laptop),   end="\n\n")
#<<<<<<<<<<<<<<<<<<
#data float
print("variabel harga laptop yaitu       :", harga_laptop, "tipe datanya yaitu     :", type(harga_laptop),  end="\n\n")
print("variabel harga keyboard yaitu     :", harga_laptop, "tipe datanya yaitu     :", type(harga_keyboard),end="\n\n")
print("variabel harga mouse yaitu        :", harga_mouse, "tipe datanya yaitu       :", type(harga_mouse),  end="\n\n")
#>>>>>>>>>>>>>>>>>>
print("----------------terimakasih----------------")